### ISSUE TITLE
3 point time series

### ISSUE THREAD

**Issue by nirwan1265** [vahuynh/dynGENIE3#5]
Is there a minimum number of time points required to run this? I have 3 time points with 3, 3, and 2 replicates. I get this error 
res <- dynGENIE3(TS.data, time.points)
Error in (num.samples.count + 1):(num.samples.count + num.samples.current) : 
  argument of length 0

**Comment by vahuynh** [comment]
Hi,

It should in principle work with 3 time points.
What is the format of your TS.data and time.points arguments?
TS.data should be a list of matrices (one matrix per experiment), where each matrix has genes as rows and time points as columns.

Since you have replicates, I think it would be preferable to average them to get one single time series (rather than considering them as 3 separate experiments). It means that TS.data will be a list containing one single matrix (containing the average gene expressions).

That being said, 3 time points is really low, and I am not sure you will learn anything meaningful from that using a pure data-driven approach like dynGENIE3.

**Comment by nirwan1265** [comment]
I averaged the replicates and changed the zeroes to the lowest value/2 and it works. 
I am running the dynGENIE3 on only significant genes and not the whole rnaseq expt. 
Thank you for you prompt reply and your help.
